/** Complete translations; missing keys are compile errors, not English fallbacks. */
import type { DesktopLocaleId } from '../desktop-locale.ts'
import type { DataHomeCopy, DataHomeDetails } from './data-home.ts'

export const additionalDataHomeLocales = {
  'pt-BR': {
    copy: {
      windowTitle: 'Escolher pasta de dados', languageLabel: 'Idioma', importTitle: 'Copiar para um ambiente independente', recommended: 'Recomendado',
      importSummary: 'Copie os dados e a lista de plugins; depois escolha quais restaurar.', reuseTitle: 'Usar esta configuração diretamente',
      reuseSummary: 'Compartilhe configurações, credenciais, conversas e plugins com a pasta selecionada.', freshTitle: 'Começar do zero', freshSummary: 'Não importar dados existentes.',
      locationLabel: 'Local dos dados', sharingLabel: 'Compartilhamento', pluginsLabel: 'Plugins existentes', buildsLabel: 'Permissões de compilação', compare: 'Ver comparação completa', back: 'Voltar', continue: 'Continuar', comparisonTitle: 'Qual é a diferença entre as opções?', suitableLabel: 'Indicado para',
      compareImportLocation: 'Copie configurações, credenciais, conversas, Skills e outros dados compatíveis para uma pasta independente do aplicativo.', compareReuseLocation: 'Use diretamente a pasta de configuração DSH selecionada.', compareFreshLocation: 'Crie uma nova pasta independente para o aplicativo.',
      compareImportSharing: 'Sem compartilhamento; as alterações posteriores são independentes.', compareReuseSharing: 'Compartilhado; alterações em qualquer aplicativo afetam o outro.', compareFreshSharing: 'Nenhum dado existente é compartilhado.',
      compareImportPlugins: 'Copie uma lista segura de restauração, sem Profiles nem ambientes de execução; depois escolha os plugins para reinstalar pela internet.', compareReusePlugins: 'Use os plugins já instalados na pasta selecionada.', compareFreshPlugins: 'Comece com um Profile vazio e instale apenas os plugins predefinidos.',
      compareImportSuitable: 'Para manter os dados em um ambiente independente.', compareReuseSuitable: 'Para manter o aplicativo e a configuração selecionada sempre alinhados.', compareFreshSuitable: 'Para configurar tudo do zero.',
      comparisonNote: 'A importação copia uma vez os dados, a lista de plugins e as permissões exatas de compilação, mantendo um Profile independente. Apenas o uso direto compartilha continuamente o ambiente de plugins.',
      acknowledge: 'Entendi', helpLabel: 'Comparar as três opções', closeLabel: 'Fechar', modeGroupLabel: 'Modo da pasta de dados', sourceDetected: 'Configuração DSH encontrada', sourceCustom: 'Outra configuração DSH selecionada', sourceMissing: 'Nenhuma configuração DSH no local padrão', sourceUnreadable: 'Não foi possível ler a pasta DSH padrão', sourceReadySummary: 'Esta pasta contém dados DSH compatíveis.', sourceMissingSummary: 'Se você usa outra pasta de dados, selecione-a manualmente.', sourceUnreadableSummary: 'Escolha uma pasta legível ou comece do zero.',
      chooseSource: 'Selecionar configuração existente', changeSource: 'Escolher outra pasta', restoreDefaultSource: 'Restaurar pasta padrão', sourceRequired: 'Selecione primeiro uma pasta de configuração existente.', sourceInvalid: 'Esta pasta não parece conter uma configuração DSH válida. Escolha outra.', sourceReadFailed: 'Não foi possível ler esta pasta. Verifique as permissões e tente novamente.', simulateMissingSource: 'Dev: simular ausência de configuração', restoreDetectedSource: 'Dev: restaurar detecção real',
      destinationTitle: 'Escolher local da configuração', destinationSummary: 'Escolha onde salvar a configuração independente. A pasta de origem não será alterada.', defaultTargetTitle: 'Local padrão', defaultTargetSummary: 'Use a pasta independente gerenciada pelo aplicativo para facilitar atualizações e reparos.', customTargetTitle: 'Pasta de configuração personalizada', customTargetSummary: 'Escolha uma pasta vazia para a configuração independente deste aplicativo.', chooseTarget: 'Escolher pasta vazia', changeTarget: 'Alterar pasta', targetRequired: 'Escolha primeiro uma pasta vazia.', targetNotEmpty: 'A pasta selecionada não está vazia. Escolha ou crie uma pasta vazia.', targetUnreadable: 'Não foi possível ler a pasta selecionada. Verifique as permissões.', targetOverlap: 'A pasta de configuração não pode estar dentro da origem da importação nem contê-la.', targetGroupLabel: 'Local da configuração',
    },
    details: {
      imported: { title: 'Copiar para um ambiente independente', location: 'Copie a configuração para uma pasta independente do aplicativo, preservando a origem.', sharing: 'Após a cópia, as alterações no aplicativo e na origem são independentes.', plugins: 'Copie a lista de restauração, sem Profile, node_modules ou arquivos de bloqueio. Reinstale os plugins após entrar; os predefinidos equivalentes não serão duplicados.', builds: 'Mescle as regras booleanas exatas de allowBuilds já validadas. Toda recusa explícita (false) será preservada.' },
      reused: { title: 'Usar esta configuração diretamente', risk: 'O aplicativo lê e grava diretamente na pasta selecionada; nenhuma cópia é criada.', location: 'Use a pasta selecionada sem criar outra configuração Harness.', sharing: 'Sem cópia: configurações, credenciais, conversas, predefinições de Agent, Skills, Profiles e plugins são lidos e gravados nesse diretório.', plugins: 'Mantenha as versões atuais; nomes iguais, aliases npm ou o mesmo repositório GitHub e subpasta não serão instalados duas vezes.', builds: 'Use as regras allowBuilds selecionadas sem mesclar nem conceder novas permissões.' },
      fresh: { title: 'Começar do zero', location: 'Crie uma pasta de dados independente e vazia.', sharing: 'Não leia nem altere configurações DSH existentes.', plugins: 'Comece com um Profile vazio e verifique apenas os plugins predefinidos.', builds: 'Adicione apenas permissões de compilação revisadas e necessárias aos plugins predefinidos.' },
    },
  },
  ja: {
    copy: {
      windowTitle: 'データフォルダーを選択', languageLabel: '言語', importTitle: '独立した環境にコピー', recommended: '推奨', importSummary: 'ユーザーデータとプラグイン一覧をコピーし、起動後に復元するプラグインを選択します。', reuseTitle: 'この設定を直接使用', reuseSummary: '選択したフォルダーと設定、認証情報、会話、プラグインを共有します。', freshTitle: '新規に開始', freshSummary: '既存のデータをインポートしません。',
      locationLabel: 'データの保存先', sharingLabel: '共有範囲', pluginsLabel: '既存のプラグイン', buildsLabel: 'ビルド権限', compare: '詳細な比較を見る', back: '戻る', continue: '次へ', comparisonTitle: '3つの選択肢の違いは？', suitableLabel: 'おすすめの用途',
      compareImportLocation: '設定、認証情報、会話、Skills などの対応データを、デスクトップ版の独立したフォルダーにコピーします。', compareReuseLocation: '選択した DSH 設定フォルダーを直接使用します。', compareFreshLocation: 'デスクトップ版専用のフォルダーを新規作成します。', compareImportSharing: '共有しません。コピー後の変更は互いに影響しません。', compareReuseSharing: '共有します。一方での変更は他方にも反映されます。', compareFreshSharing: '既存のデータは共有しません。',
      compareImportPlugins: 'Profile や実行環境を除く安全な復元一覧をコピーし、起動後にオンラインで再インストールするプラグインを選択します。', compareReusePlugins: '選択したフォルダーの既存プラグインを使用します。', compareFreshPlugins: '空の Profile から開始し、プリセットのプラグインのみをインストールします。', compareImportSuitable: 'データを保持しながらデスクトップ版を独立させたい方。', compareReuseSuitable: 'デスクトップ版と選択した DSH 設定を常に一致させたい方。', compareFreshSuitable: '最初から設定したい方。', comparisonNote: 'インポートはデータ、プラグイン一覧、厳密なビルド権限を一度だけコピーし、独立した Profile を維持します。プラグイン環境を継続して共有するのは直接使用の場合のみです。',
      acknowledge: '確認', helpLabel: '3つの選択肢を比較', closeLabel: '閉じる', modeGroupLabel: 'データフォルダーの使用方法', sourceDetected: 'DSH 設定が見つかりました', sourceCustom: '別の DSH 設定を選択済み', sourceMissing: '既定の場所に DSH 設定がありません', sourceUnreadable: '既定の DSH 設定フォルダーを読み取れません', sourceReadySummary: 'このフォルダーには対応する DSH データがあります。', sourceMissingSummary: '別のデータフォルダーを使用している場合は、手動で選択できます。', sourceUnreadableSummary: '読み取り可能なフォルダーを選択するか、新規に開始してください。', chooseSource: '既存の設定を選択', changeSource: '別のフォルダーを選択', restoreDefaultSource: '既定のフォルダーに戻す', sourceRequired: '先に既存の設定フォルダーを選択してください。', sourceInvalid: '有効な DSH 設定フォルダーではないようです。別のフォルダーを選択してください。', sourceReadFailed: '読み取れません。フォルダーの権限を確認して再試行してください。', simulateMissingSource: '開発：設定なしを再現', restoreDetectedSource: '開発：実際の検出結果に戻す',
      destinationTitle: '設定の保存先を選択', destinationSummary: '独立した設定の保存先を選択します。元のフォルダーは変更しません。', defaultTargetTitle: '既定の保存先', defaultTargetSummary: '更新や修復が容易な、デスクトップ版が管理する独立したフォルダーを使用します。', customTargetTitle: 'カスタム設定フォルダー', customTargetSummary: 'このクライアント専用の設定を保存する空のフォルダーを選択します。', chooseTarget: '空のフォルダーを選択', changeTarget: 'フォルダーを変更', targetRequired: '先に空のフォルダーを選択してください。', targetNotEmpty: 'フォルダーが空ではありません。空のフォルダーを選択または作成してください。', targetUnreadable: '選択したフォルダーを読み取れません。権限を確認してください。', targetOverlap: '保存先はインポート元の内部に置くことも、インポート元を含むこともできません。', targetGroupLabel: '設定の保存先',
    },
    details: {
      imported: { title: '独立した環境にコピー', location: '元のフォルダーを保持して、デスクトップ版の独立したフォルダーにコピーします。', sharing: 'コピー後は共有されず、双方の変更は互いに影響しません。', plugins: 'Profile、node_modules、ロックファイルを除く復元一覧をコピーします。起動後に再インストールでき、同じプリセットは重複しません。', builds: '検証済みの厳密な allowBuilds 真偽値ルールを統合します。明示的な拒否（false）は緩和しません。' },
      reused: { title: 'この設定を直接使用', risk: '選択したフォルダーをアプリが直接読み書きし、コピーは作成しません。', location: '別の Harness 設定を作らず、選択したフォルダーを直接使用します。', sharing: 'コピーせず、選択したフォルダーの設定、認証情報、会話、Agent プリセット、Skills、Profile、プラグインを直接読み書きします。', plugins: '現在のバージョンを保持します。同名、npm alias、同じ GitHub リポジトリとサブパスは重複インストールしません。', builds: '選択した設定の allowBuilds をそのまま使い、統合や新たな許可は行いません。' },
      fresh: { title: '新規に開始', location: 'デスクトップ版の独立した空のフォルダーを作成します。', sharing: '既存の DSH 設定を読み取ったり変更したりしません。', plugins: '空の Profile から開始し、プリセットのプラグインのみを確認します。', builds: 'プリセットに必要で審査済みのビルド権限のみを追加します。' },
    },
  },
  ko: {
    copy: {
      windowTitle: '데이터 폴더 선택', languageLabel: '언어', importTitle: '독립 환경으로 복사', recommended: '권장', importSummary: '사용자 데이터와 플러그인 목록을 복사한 후 복원할 플러그인을 선택합니다.', reuseTitle: '이 설정을 직접 사용', reuseSummary: '선택한 폴더와 설정, 인증 정보, 대화 및 플러그인을 공유합니다.', freshTitle: '새로 시작', freshSummary: '기존 데이터를 가져오지 않습니다.', locationLabel: '데이터 위치', sharingLabel: '공유 범위', pluginsLabel: '기존 플러그인', buildsLabel: '빌드 권한', compare: '전체 비교 보기', back: '뒤로', continue: '계속', comparisonTitle: '세 가지 옵션은 어떻게 다른가요?', suitableLabel: '추천 대상',
      compareImportLocation: '설정, 인증 정보, 대화, Skills 등 지원되는 데이터를 데스크톱 전용 폴더로 복사합니다.', compareReuseLocation: '선택한 DSH 설정 폴더를 직접 사용합니다.', compareFreshLocation: '새 데스크톱 전용 폴더를 만듭니다.', compareImportSharing: '공유하지 않습니다. 복사 후 변경 사항은 서로 영향을 주지 않습니다.', compareReuseSharing: '공유합니다. 한쪽의 변경이 다른 쪽에도 영향을 줍니다.', compareFreshSharing: '기존 데이터를 공유하지 않습니다.', compareImportPlugins: 'Profile이나 실행 환경 없이 안전한 복원 목록을 복사하고, 진입 후 온라인으로 재설치할 플러그인을 선택합니다.', compareReusePlugins: '선택한 폴더에 설치된 플러그인을 사용합니다.', compareFreshPlugins: '빈 Profile로 시작하고 기본 제공 플러그인만 설치합니다.', compareImportSuitable: '데이터를 유지하면서 데스크톱 환경을 분리하려는 사용자.', compareReuseSuitable: '데스크톱과 선택한 DSH 설정을 항상 일치시키려는 사용자.', compareFreshSuitable: '처음부터 설정하려는 사용자.', comparisonNote: '가져오기는 데이터, 플러그인 목록과 정확한 빌드 권한을 한 번 복사하고 독립 Profile을 유지합니다. 직접 사용만 플러그인 환경을 계속 공유합니다.',
      acknowledge: '확인', helpLabel: '세 가지 옵션 비교', closeLabel: '닫기', modeGroupLabel: '데이터 폴더 사용 방식', sourceDetected: 'DSH 설정을 찾았습니다', sourceCustom: '다른 DSH 설정을 선택했습니다', sourceMissing: '기본 위치에 DSH 설정이 없습니다', sourceUnreadable: '기본 DSH 설정 폴더를 읽을 수 없습니다', sourceReadySummary: '이 폴더에는 지원되는 DSH 데이터가 있습니다.', sourceMissingSummary: '다른 데이터 폴더를 사용한다면 직접 선택할 수 있습니다.', sourceUnreadableSummary: '읽을 수 있는 폴더를 선택하거나 새로 시작하세요.', chooseSource: '기존 설정 선택', changeSource: '다른 폴더 선택', restoreDefaultSource: '기본 폴더로 복원', sourceRequired: '먼저 기존 설정 폴더를 선택하세요.', sourceInvalid: '유효한 DSH 설정 폴더가 아닌 것 같습니다. 다른 폴더를 선택하세요.', sourceReadFailed: '폴더를 읽을 수 없습니다. 권한을 확인하고 다시 시도하세요.', simulateMissingSource: '개발: 설정 없음 재현', restoreDetectedSource: '개발: 실제 검색 결과 복원',
      destinationTitle: '설정 저장 위치 선택', destinationSummary: '독립 설정을 저장할 위치를 선택합니다. 원본 폴더는 변경되지 않습니다.', defaultTargetTitle: '기본 위치', defaultTargetSummary: '업데이트와 복구가 편리한 데스크톱 관리 전용 폴더를 사용합니다.', customTargetTitle: '사용자 지정 설정 폴더', customTargetSummary: '이 클라이언트의 독립 설정을 저장할 빈 폴더를 선택합니다.', chooseTarget: '빈 폴더 선택', changeTarget: '폴더 변경', targetRequired: '먼저 빈 폴더를 선택하세요.', targetNotEmpty: '선택한 폴더가 비어 있지 않습니다. 빈 폴더를 선택하거나 만드세요.', targetUnreadable: '선택한 폴더를 읽을 수 없습니다. 권한을 확인하세요.', targetOverlap: '설정 폴더는 가져오기 원본 안에 있거나 원본을 포함할 수 없습니다.', targetGroupLabel: '설정 위치',
    },
    details: {
      imported: { title: '독립 환경으로 복사', location: '원본을 그대로 두고 데스크톱 전용 데이터 폴더로 복사합니다.', sharing: '복사 후 공유되지 않으며 양쪽의 변경 사항은 독립적입니다.', plugins: 'Profile, node_modules, 잠금 파일 없이 복원 목록을 복사합니다. 진입 후 재설치하며 동일한 기본 제공 항목은 중복 설치하지 않습니다.', builds: '검증된 정확한 allowBuilds 불리언 규칙을 병합합니다. 명시적인 거부(false)는 완화하지 않습니다.' },
      reused: { title: '이 설정을 직접 사용', risk: '앱이 선택한 폴더를 직접 읽고 쓰며 복사본을 만들지 않습니다.', location: '두 번째 Harness 설정을 만들지 않고 선택한 폴더를 사용합니다.', sharing: '복사하지 않고 선택한 폴더의 설정, 인증 정보, 대화, Agent 프리셋, Skills, Profile 및 플러그인을 직접 읽고 쓸니다.', plugins: '현재 버전을 유지합니다. 같은 이름, npm alias 또는 같은 GitHub 저장소와 하위 경로는 중복 설치하지 않습니다.', builds: '선택한 구성의 allowBuilds를 그대로 사용하며 병합하거나 새 권한을 추가하지 않습니다.' },
      fresh: { title: '새로 시작', location: '독립적인 빈 데스크톱 데이터 폴더를 만듭니다.', sharing: '기존 DSH 설정을 읽거나 변경하지 않습니다.', plugins: '빈 Profile로 시작하고 기본 제공 플러그인만 확인합니다.', builds: '기본 제공 플러그인에 필요한 검토된 빌드 권한만 추가합니다.' },
    },
  },
  es: {
    copy: {
      windowTitle: 'Elegir carpeta de datos', languageLabel: 'Idioma', importTitle: 'Copiar a un entorno independiente', recommended: 'Recomendado', importSummary: 'Copia los datos y la lista de plugins; después elige cuáles restaurar.', reuseTitle: 'Usar esta configuración directamente', reuseSummary: 'Comparte ajustes, credenciales, conversaciones y plugins con la carpeta seleccionada.', freshTitle: 'Empezar de cero', freshSummary: 'No importar datos existentes.', locationLabel: 'Ubicación de los datos', sharingLabel: 'Uso compartido', pluginsLabel: 'Plugins existentes', buildsLabel: 'Permisos de compilación', compare: 'Ver comparación completa', back: 'Atrás', continue: 'Continuar', comparisonTitle: '¿En qué se diferencian las opciones?', suitableLabel: 'Recomendado para',
      compareImportLocation: 'Copia ajustes, credenciales, conversaciones, Skills y otros datos compatibles a una carpeta independiente de la aplicación.', compareReuseLocation: 'Usa directamente la carpeta de configuración DSH seleccionada.', compareFreshLocation: 'Crea una nueva carpeta independiente para la aplicación.', compareImportSharing: 'No se comparte; los cambios posteriores son independientes.', compareReuseSharing: 'Se comparte; los cambios en un lado afectan al otro.', compareFreshSharing: 'No se comparte ningún dato existente.', compareImportPlugins: 'Copia una lista de restauración segura, sin Profiles ni entornos de ejecución; después elige los plugins que reinstalar por internet.', compareReusePlugins: 'Usa los plugins ya instalados en la carpeta seleccionada.', compareFreshPlugins: 'Empieza con un Profile vacío e instala solo los plugins predefinidos.', compareImportSuitable: 'Conservar los datos en un entorno independiente.', compareReuseSuitable: 'Mantener la aplicación y la configuración seleccionada siempre sincronizadas.', compareFreshSuitable: 'Configurar todo desde cero.', comparisonNote: 'La importación copia una vez los datos, la lista de plugins y los permisos exactos de compilación, manteniendo un Profile independiente. Solo el uso directo comparte continuamente el entorno de plugins.',
      acknowledge: 'Entendido', helpLabel: 'Comparar las tres opciones', closeLabel: 'Cerrar', modeGroupLabel: 'Modo de la carpeta de datos', sourceDetected: 'Configuración DSH encontrada', sourceCustom: 'Otra configuración DSH seleccionada', sourceMissing: 'No hay configuración DSH en la ubicación predeterminada', sourceUnreadable: 'No se puede leer la carpeta DSH predeterminada', sourceReadySummary: 'Esta carpeta contiene datos DSH compatibles.', sourceMissingSummary: 'Si usas otra carpeta de datos, puedes seleccionarla manualmente.', sourceUnreadableSummary: 'Elige una carpeta legible o empieza de cero.', chooseSource: 'Elegir configuración existente', changeSource: 'Elegir otra carpeta', restoreDefaultSource: 'Restaurar carpeta predeterminada', sourceRequired: 'Primero elige una carpeta de configuración existente.', sourceInvalid: 'Esta carpeta no parece contener una configuración DSH válida. Elige otra.', sourceReadFailed: 'No se puede leer esta carpeta. Revisa los permisos e inténtalo de nuevo.', simulateMissingSource: 'Des.: simular ausencia de configuración', restoreDetectedSource: 'Des.: restaurar detección real',
      destinationTitle: 'Elegir ubicación de configuración', destinationSummary: 'Elige dónde guardar la configuración independiente. La carpeta de origen no se modificará.', defaultTargetTitle: 'Ubicación predeterminada', defaultTargetSummary: 'Usa la carpeta independiente gestionada por la aplicación para facilitar actualizaciones y reparaciones.', customTargetTitle: 'Carpeta de configuración personalizada', customTargetSummary: 'Elige una carpeta vacía para la configuración independiente de este cliente.', chooseTarget: 'Elegir carpeta vacía', changeTarget: 'Cambiar carpeta', targetRequired: 'Primero elige una carpeta vacía.', targetNotEmpty: 'La carpeta no está vacía. Elige o crea una carpeta vacía.', targetUnreadable: 'No se puede leer la carpeta seleccionada. Revisa los permisos.', targetOverlap: 'La carpeta de configuración no puede estar dentro del origen de importación ni contenerlo.', targetGroupLabel: 'Ubicación de configuración',
    },
    details: {
      imported: { title: 'Copiar a un entorno independiente', location: 'Copia la configuración a una carpeta independiente de la aplicación sin modificar el origen.', sharing: 'Tras la copia, los cambios en la aplicación y en el origen son independientes.', plugins: 'Copia la lista de restauración sin Profile, node_modules ni archivos de bloqueo. Reinstala los plugins al entrar; los predefinidos equivalentes no se duplican.', builds: 'Combina las reglas booleanas exactas de allowBuilds ya validadas. Se conservan todas las denegaciones explícitas (false).' },
      reused: { title: 'Usar esta configuración directamente', risk: 'La aplicación lee y escribe directamente en la carpeta seleccionada; no crea una copia.', location: 'Usa la carpeta seleccionada sin crear otra configuración Harness.', sharing: 'Sin copia: ajustes, credenciales, conversaciones, preajustes de Agent, Skills, Profiles y plugins se leen y escriben en esa carpeta.', plugins: 'Conserva las versiones actuales; no duplica nombres, alias npm ni el mismo repositorio GitHub y subruta.', builds: 'Usa las reglas allowBuilds seleccionadas tal cual, sin combinarlas ni conceder permisos nuevos.' },
      fresh: { title: 'Empezar de cero', location: 'Crea una carpeta de datos independiente y vacía.', sharing: 'No lee ni modifica configuraciones DSH existentes.', plugins: 'Empieza con un Profile vacío y comprueba solo los plugins predefinidos.', builds: 'Añade solo permisos de compilación revisados y necesarios para los plugins predefinidos.' },
    },
  },
  fr: {
    copy: {
      windowTitle: 'Choisir le dossier de données', languageLabel: 'Langue', importTitle: 'Copier dans un environnement indépendant', recommended: 'Recommandé', importSummary: 'Copiez les données et la liste des plugins, puis choisissez ceux à restaurer.', reuseTitle: 'Utiliser directement cette configuration', reuseSummary: 'Partagez réglages, identifiants, conversations et plugins avec le dossier choisi.', freshTitle: 'Repartir de zéro', freshSummary: 'Ne pas importer de données existantes.', locationLabel: 'Emplacement des données', sharingLabel: 'Partage', pluginsLabel: 'Plugins existants', buildsLabel: 'Autorisations de compilation', compare: 'Voir la comparaison complète', back: 'Retour', continue: 'Continuer', comparisonTitle: 'Quelles différences entre ces options ?', suitableLabel: 'Pour qui',
      compareImportLocation: 'Copiez les réglages, identifiants, conversations, Skills et autres données compatibles dans un dossier indépendant de l’application.', compareReuseLocation: 'Utilisez directement le dossier de configuration DSH choisi.', compareFreshLocation: 'Créez un nouveau dossier indépendant pour l’application.', compareImportSharing: 'Aucun partage ; les modifications ultérieures sont indépendantes.', compareReuseSharing: 'Partagé ; les modifications d’un côté affectent l’autre.', compareFreshSharing: 'Aucune donnée existante n’est partagée.', compareImportPlugins: 'Copiez une liste de restauration sûre sans Profiles ni environnements d’exécution, puis choisissez les plugins à réinstaller en ligne.', compareReusePlugins: 'Utilisez les plugins déjà installés dans le dossier choisi.', compareFreshPlugins: 'Commencez avec un Profile vide et installez uniquement les plugins prédéfinis.', compareImportSuitable: 'Conserver les données dans un environnement indépendant.', compareReuseSuitable: 'Garder l’application et la configuration choisie toujours alignées.', compareFreshSuitable: 'Tout configurer depuis le début.', comparisonNote: 'L’importation copie une fois les données, la liste des plugins et les autorisations exactes de compilation, tout en gardant un Profile indépendant. Seule l’utilisation directe partage durablement l’environnement des plugins.',
      acknowledge: 'Compris', helpLabel: 'Comparer les trois options', closeLabel: 'Fermer', modeGroupLabel: 'Mode du dossier de données', sourceDetected: 'Configuration DSH détectée', sourceCustom: 'Autre configuration DSH sélectionnée', sourceMissing: 'Aucune configuration DSH à l’emplacement par défaut', sourceUnreadable: 'Impossible de lire le dossier DSH par défaut', sourceReadySummary: 'Ce dossier contient des données DSH compatibles.', sourceMissingSummary: 'Si vous utilisez un autre dossier, vous pouvez le sélectionner manuellement.', sourceUnreadableSummary: 'Choisissez un dossier lisible ou repartez de zéro.', chooseSource: 'Choisir une configuration existante', changeSource: 'Choisir un autre dossier', restoreDefaultSource: 'Rétablir le dossier par défaut', sourceRequired: 'Choisissez d’abord un dossier de configuration existant.', sourceInvalid: 'Ce dossier ne semble pas contenir une configuration DSH valide. Choisissez-en un autre.', sourceReadFailed: 'Impossible de lire ce dossier. Vérifiez les autorisations et réessayez.', simulateMissingSource: 'Dév. : simuler une configuration absente', restoreDetectedSource: 'Dév. : rétablir la détection réelle',
      destinationTitle: 'Choisir l’emplacement de la configuration', destinationSummary: 'Choisissez où enregistrer la configuration indépendante. Le dossier source reste inchangé.', defaultTargetTitle: 'Emplacement par défaut', defaultTargetSummary: 'Utilisez le dossier indépendant géré par l’application pour faciliter les mises à jour et réparations.', customTargetTitle: 'Dossier de configuration personnalisé', customTargetSummary: 'Choisissez un dossier vide pour la configuration indépendante de ce client.', chooseTarget: 'Choisir un dossier vide', changeTarget: 'Changer de dossier', targetRequired: 'Choisissez d’abord un dossier vide.', targetNotEmpty: 'Le dossier n’est pas vide. Choisissez ou créez un dossier vide.', targetUnreadable: 'Impossible de lire le dossier choisi. Vérifiez les autorisations.', targetOverlap: 'Le dossier de configuration ne peut ni se trouver dans la source d’importation ni la contenir.', targetGroupLabel: 'Emplacement de la configuration',
    },
    details: {
      imported: { title: 'Copier dans un environnement indépendant', location: 'Copiez la configuration dans un dossier indépendant de l’application sans modifier la source.', sharing: 'Après la copie, les changements dans l’application et dans la source restent indépendants.', plugins: 'Copiez la liste de restauration sans Profile, node_modules ni fichiers de verrouillage. Réinstallez les plugins après l’ouverture ; les plugins prédéfinis équivalents ne seront pas dupliqués.', builds: 'Fusionnez les règles booléennes exactes allowBuilds validées. Tout refus explicite (false) est conservé.' },
      reused: { title: 'Utiliser directement cette configuration', risk: 'L’application lit et écrit directement dans le dossier choisi ; aucune copie n’est créée.', location: 'Utilisez le dossier choisi sans créer une seconde configuration Harness.', sharing: 'Sans copie : réglages, identifiants, conversations, préréglages Agent, Skills, Profiles et plugins sont lus et écrits dans ce dossier.', plugins: 'Conservez les versions actuelles ; les noms identiques, alias npm ou mêmes dépôts GitHub et sous-chemins ne sont pas installés deux fois.', builds: 'Utilisez les règles allowBuilds du dossier telles quelles, sans fusion ni nouvelle autorisation.' },
      fresh: { title: 'Repartir de zéro', location: 'Créez un dossier de données indépendant et vide.', sharing: 'Aucune configuration DSH existante n’est lue ou modifiée.', plugins: 'Commencez avec un Profile vide et vérifiez uniquement les plugins prédéfinis.', builds: 'Ajoutez uniquement les autorisations de compilation vérifiées et nécessaires aux plugins prédéfinis.' },
    },
  },
  de: {
    copy: {
      windowTitle: 'Datenordner auswählen', languageLabel: 'Sprache', importTitle: 'In eine eigenständige Umgebung kopieren', recommended: 'Empfohlen', importSummary: 'Benutzerdaten und Plugin-Liste kopieren; anschließend Plugins zur Wiederherstellung auswählen.', reuseTitle: 'Diese Konfiguration direkt verwenden', reuseSummary: 'Einstellungen, Zugangsdaten, Gespräche und Plugins mit dem gewählten Ordner teilen.', freshTitle: 'Neu beginnen', freshSummary: 'Keine vorhandenen Daten importieren.', locationLabel: 'Speicherort', sharingLabel: 'Gemeinsame Nutzung', pluginsLabel: 'Vorhandene Plugins', buildsLabel: 'Build-Berechtigungen', compare: 'Vollständigen Vergleich anzeigen', back: 'Zurück', continue: 'Weiter', comparisonTitle: 'Wie unterscheiden sich die drei Optionen?', suitableLabel: 'Geeignet für',
      compareImportLocation: 'Einstellungen, Zugangsdaten, Gespräche, Skills und weitere unterstützte Daten in einen eigenständigen Desktop-Ordner kopieren.', compareReuseLocation: 'Den gewählten DSH-Konfigurationsordner direkt verwenden.', compareFreshLocation: 'Einen neuen eigenständigen Desktop-Ordner erstellen.', compareImportSharing: 'Nicht geteilt; spätere Änderungen sind unabhängig.', compareReuseSharing: 'Geteilt; Änderungen wirken sich auf beide Seiten aus.', compareFreshSharing: 'Vorhandene Daten werden nicht geteilt.', compareImportPlugins: 'Eine sichere Wiederherstellungsliste ohne Profiles und Laufzeitumgebungen kopieren; später Plugins zur Online-Neuinstallation auswählen.', compareReusePlugins: 'Bereits im gewählten Ordner installierte Plugins verwenden.', compareFreshPlugins: 'Mit leerem Profile beginnen und nur voreingestellte Plugins installieren.', compareImportSuitable: 'Daten behalten und die Desktop-Umgebung getrennt nutzen.', compareReuseSuitable: 'Desktop und gewählte DSH-Konfiguration dauerhaft gemeinsam nutzen.', compareFreshSuitable: 'Alles von Grund auf einrichten.', comparisonNote: 'Beim Import werden Daten, Plugin-Liste und genaue Build-Berechtigungen einmalig kopiert; das Profile bleibt eigenständig. Nur die direkte Verwendung teilt die Plugin-Umgebung dauerhaft.',
      acknowledge: 'Verstanden', helpLabel: 'Drei Optionen vergleichen', closeLabel: 'Schließen', modeGroupLabel: 'Datenordner-Modus', sourceDetected: 'DSH-Konfiguration gefunden', sourceCustom: 'Andere DSH-Konfiguration ausgewählt', sourceMissing: 'Keine DSH-Konfiguration am Standardspeicherort', sourceUnreadable: 'DSH-Standardordner kann nicht gelesen werden', sourceReadySummary: 'Dieser Ordner enthält unterstützte DSH-Daten.', sourceMissingSummary: 'Einen anderen Datenordner können Sie manuell auswählen.', sourceUnreadableSummary: 'Wählen Sie einen lesbaren Ordner oder beginnen Sie neu.', chooseSource: 'Vorhandene Konfiguration wählen', changeSource: 'Anderen Ordner wählen', restoreDefaultSource: 'Standardordner wiederherstellen', sourceRequired: 'Wählen Sie zuerst einen vorhandenen Konfigurationsordner.', sourceInvalid: 'Dies scheint kein gültiger DSH-Konfigurationsordner zu sein. Wählen Sie einen anderen.', sourceReadFailed: 'Der Ordner kann nicht gelesen werden. Prüfen Sie die Berechtigungen und versuchen Sie es erneut.', simulateMissingSource: 'Entw.: fehlende Konfiguration simulieren', restoreDetectedSource: 'Entw.: echte Erkennung wiederherstellen',
      destinationTitle: 'Konfigurationsspeicherort wählen', destinationSummary: 'Legen Sie fest, wo die eigenständige Konfiguration gespeichert wird. Der Quellordner bleibt unverändert.', defaultTargetTitle: 'Standardspeicherort', defaultTargetSummary: 'Der von Desktop verwaltete eigenständige Ordner vereinfacht Updates und Reparaturen.', customTargetTitle: 'Benutzerdefinierter Konfigurationsordner', customTargetSummary: 'Wählen Sie einen leeren Ordner für die eigenständige Konfiguration dieses Clients.', chooseTarget: 'Leeren Ordner wählen', changeTarget: 'Ordner ändern', targetRequired: 'Wählen Sie zuerst einen leeren Ordner.', targetNotEmpty: 'Der Ordner ist nicht leer. Wählen oder erstellen Sie einen leeren Ordner.', targetUnreadable: 'Der gewählte Ordner kann nicht gelesen werden. Prüfen Sie die Berechtigungen.', targetOverlap: 'Der Konfigurationsordner darf weder innerhalb der Importquelle liegen noch diese enthalten.', targetGroupLabel: 'Konfigurationsspeicherort',
    },
    details: {
      imported: { title: 'In eine eigenständige Umgebung kopieren', location: 'In einen eigenständigen Desktop-Datenordner kopieren; die Quelle bleibt unverändert.', sharing: 'Nach dem Kopieren sind Änderungen auf beiden Seiten unabhängig.', plugins: 'Wiederherstellungsliste ohne Profile, node_modules und Sperrdateien kopieren. Plugins nach dem Start neu installieren; gleiche voreingestellte Plugins werden nicht dupliziert.', builds: 'Validierte, genaue boolesche allowBuilds-Regeln zusammenführen. Jede ausdrückliche Ablehnung (false) bleibt erhalten.' },
      reused: { title: 'Diese Konfiguration direkt verwenden', risk: 'Die App liest und schreibt direkt im gewählten Ordner; es wird keine Kopie erstellt.', location: 'Den gewählten Ordner verwenden, ohne eine zweite Harness-Konfiguration zu erstellen.', sharing: 'Ohne Kopie: Einstellungen, Zugangsdaten, Gespräche, Agent-Voreinstellungen, Skills, Profiles und Plugins werden direkt in diesem Ordner gelesen und geschrieben.', plugins: 'Aktuelle Versionen behalten; gleiche Namen, npm-Aliasse oder identische GitHub-Repositories und Unterpfade werden nicht doppelt installiert.', builds: 'Die allowBuilds-Regeln des gewählten Ordners unverändert verwenden, ohne Zusammenführung oder neue Berechtigungen.' },
      fresh: { title: 'Neu beginnen', location: 'Einen leeren, eigenständigen Desktop-Datenordner erstellen.', sharing: 'Vorhandene DSH-Konfigurationen werden weder gelesen noch verändert.', plugins: 'Mit leerem Profile beginnen und nur voreingestellte Plugins prüfen.', builds: 'Nur geprüfte Build-Berechtigungen hinzufügen, die voreingestellte Plugins benötigen.' },
    },
  },
  ru: {
    copy: {
      windowTitle: 'Выбор папки данных', languageLabel: 'Язык', importTitle: 'Скопировать в отдельную среду', recommended: 'Рекомендуется', importSummary: 'Скопируйте данные и список плагинов, затем выберите плагины для восстановления.', reuseTitle: 'Использовать эту конфигурацию напрямую', reuseSummary: 'Общие настройки, учётные данные, диалоги и плагины с выбранной папкой.', freshTitle: 'Начать с нуля', freshSummary: 'Не импортировать существующие данные.', locationLabel: 'Расположение данных', sharingLabel: 'Совместное использование', pluginsLabel: 'Существующие плагины', buildsLabel: 'Разрешения на сборку', compare: 'Полное сравнение', back: 'Назад', continue: 'Продолжить', comparisonTitle: 'Чем отличаются эти варианты?', suitableLabel: 'Для кого',
      compareImportLocation: 'Скопировать настройки, учётные данные, диалоги, Skills и другие поддерживаемые данные в отдельную папку приложения.', compareReuseLocation: 'Использовать выбранную папку конфигурации DSH напрямую.', compareFreshLocation: 'Создать новую отдельную папку приложения.', compareImportSharing: 'Не общие; после копирования изменения независимы.', compareReuseSharing: 'Общие; изменения с одной стороны влияют на другую.', compareFreshSharing: 'Существующие данные не используются совместно.', compareImportPlugins: 'Скопировать безопасный список восстановления без Profiles и сред выполнения; затем выбрать плагины для переустановки через интернет.', compareReusePlugins: 'Использовать плагины, уже установленные в выбранной папке.', compareFreshPlugins: 'Начать с пустого Profile и установить только предустановленные плагины.', compareImportSuitable: 'Сохранить данные и отделить среду приложения.', compareReuseSuitable: 'Постоянно использовать общую конфигурацию DSH.', compareFreshSuitable: 'Настроить всё с самого начала.', comparisonNote: 'Импорт один раз копирует данные, список плагинов и точные разрешения на сборку, сохраняя отдельный Profile. Только прямое использование постоянно разделяет среду плагинов.',
      acknowledge: 'Понятно', helpLabel: 'Сравнить три варианта', closeLabel: 'Закрыть', modeGroupLabel: 'Режим папки данных', sourceDetected: 'Найдена конфигурация DSH', sourceCustom: 'Выбрана другая конфигурация DSH', sourceMissing: 'В стандартной папке нет конфигурации DSH', sourceUnreadable: 'Не удалось прочитать стандартную папку DSH', sourceReadySummary: 'Папка содержит поддерживаемые данные DSH.', sourceMissingSummary: 'Если данные находятся в другой папке, выберите её вручную.', sourceUnreadableSummary: 'Выберите доступную для чтения папку или начните с нуля.', chooseSource: 'Выбрать существующую конфигурацию', changeSource: 'Выбрать другую папку', restoreDefaultSource: 'Вернуть стандартную папку', sourceRequired: 'Сначала выберите существующую папку конфигурации.', sourceInvalid: 'Это не похоже на допустимую папку конфигурации DSH. Выберите другую.', sourceReadFailed: 'Не удалось прочитать папку. Проверьте права доступа и повторите попытку.', simulateMissingSource: 'Разработка: имитировать отсутствие настроек', restoreDetectedSource: 'Разработка: вернуть реальное обнаружение',
      destinationTitle: 'Выбор расположения конфигурации', destinationSummary: 'Выберите место для отдельной конфигурации приложения. Исходная папка не изменится.', defaultTargetTitle: 'Стандартное расположение', defaultTargetSummary: 'Отдельная папка, управляемая приложением, упрощает обновления и восстановление.', customTargetTitle: 'Другая папка конфигурации', customTargetSummary: 'Выберите пустую папку для отдельной конфигурации этого клиента.', chooseTarget: 'Выбрать пустую папку', changeTarget: 'Сменить папку', targetRequired: 'Сначала выберите пустую папку.', targetNotEmpty: 'Папка не пуста. Выберите или создайте пустую папку.', targetUnreadable: 'Не удалось прочитать выбранную папку. Проверьте права доступа.', targetOverlap: 'Папка конфигурации не может находиться внутри источника импорта или содержать его.', targetGroupLabel: 'Расположение конфигурации',
    },
    details: {
      imported: { title: 'Скопировать в отдельную среду', location: 'Скопировать конфигурацию в отдельную папку приложения, не меняя источник.', sharing: 'После копирования изменения в приложении и источнике независимы.', plugins: 'Копируется список восстановления без Profile, node_modules и файлов блокировки. После входа можно переустановить плагины; совпадающие предустановленные плагины не дублируются.', builds: 'Объединяются проверенные точные логические правила allowBuilds. Каждый явный запрет (false) сохраняется.' },
      reused: { title: 'Использовать эту конфигурацию напрямую', risk: 'Приложение читает и записывает данные прямо в выбранной папке; копия не создаётся.', location: 'Использовать выбранную папку без создания второй конфигурации Harness.', sharing: 'Без копии: настройки, учётные данные, диалоги, пресеты Agent, Skills, Profiles и плагины читаются и записываются в этой папке.', plugins: 'Текущие версии сохраняются; одинаковые имена, псевдонимы npm или совпадающие репозитории GitHub и подпути повторно не устанавливаются.', builds: 'Используются имеющиеся в выбранной конфигурации правила allowBuilds без объединения и новых разрешений.' },
      fresh: { title: 'Начать с нуля', location: 'Создать отдельную пустую папку данных приложения.', sharing: 'Существующие конфигурации DSH не читаются и не изменяются.', plugins: 'Начать с пустого Profile и проверить только предустановленные плагины.', builds: 'Добавить только проверенные разрешения на сборку, необходимые предустановленным плагинам.' },
    },
  },
} satisfies Record<Exclude<DesktopLocaleId, 'zh' | 'en'>, { copy: DataHomeCopy; details: DataHomeDetails }>
